name: Android CI

on: push: branches: [ main ]
workflow_dispatch:

jobs: build: name: Build LSPosed Module runs-on: ubuntu-latest

steps:
- name: Checkout repository
  uses: actions/checkout@v3

- name: Set up JDK 11
  uses: actions/setup-java@v3
  with:
    distribution: 'temurin'
    java-version: '11'

- name: Download Android SDK
  uses: android-actions/setup-android@v2
  with:
    api-level: 33
    components: platform-tools, build-tools-33.0.0, android-33

- name: Grant execute permission for Gradlew
  run: chmod +x gradlew

- name: Build APK
  run: |
    ./gradlew clean assembleRelease

- name: Upload Artifact
  uses: actions/upload-artifact@v3
  with:
    name: harpa-auto-absen-apk
    path: app/build/outputs/apk/release/app-release.apk

